name: Deploy develop to Azure Web App (lsh slot)

on:
  push:
    branches: [ develop ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (Nest -> dist)
        run: npm run build

      - name: Package for Azure
        # prisma 폴더까지 함께 압축 (마이그레이션/프리즈마 스키마 필요시)
        run: zip -r release.zip dist package.json package-lock.json prisma

      - name: "Deploy to Azure Web App (slot: lsh)"
        uses: azure/webapps-deploy@v3
        with:
          app-name: worldstudy
          slot-name: lsh
          package: release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_LSH }}
